AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template that configures the Unicorn Store DevSecOps workshop. 

Resources:

  ModernizationVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://modernization-workshop-bucket.s3-us-west-2.amazonaws.com/cfn/v1/modernization-vpc.yaml
    
  ModernizationCloud9:
    DependsOn: ModernizationVPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://modernization-workshop-bucket.s3-us-west-2.amazonaws.com/cfn/v1/modernization-cloud9.yaml

Outputs: {}