AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template configures a VPC and cloud9 instance. 

Resources:

  ModernizationVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://modernization-workshop-bucket.s3-us-west-2.amazonaws.com/cfn/vpc/vpc.yaml
      Parameters:
        EnvironmentName: Workshop
    
  ModernizationCloud9:
    DependsOn: ModernizationVPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://modernization-workshop-bucket.s3-us-west-2.amazonaws.com/cfn/cloud9/cloud9.yaml
      Parameters:
        PublicSubnet1: !GetAtt ModernizationVPC.Outputs.PublicSubnet1

Outputs: {}