name: Deploy preview to AWS S3

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Preview of the build'     
        required: false
        type: boolean

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-18.04

    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out main
        uses: actions/checkout@v2
      
      - name: Build
        run: hugo --minify
        
      - name: Deploy
        run: sh ./create-and-and-deploy-s3-website.sh
